# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a770df395a6e8989c0c7a873ee2af2966d163adfeda10eee85873e38a03c3b7ffa541abbd8579614f787e7bbbc4bbc0ca9896f157580ef75bd0d7242409901d9

test:
  secret_key_base: 82bc3aa39b3d4915cba06a3708e9c34fec7888ef2cc824706ba655df1ffc26c68d4b92cd29d1c97a45ab6ca5120b44a829f16718107ca00eabc80502169ff315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
